### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by zrc9627** [yuto3o/SKNet-Keras#4]
i use this code to resnet,but i got a error. this is my code
`def SKConv(M=2, r=16, L=32, G=32, name='skconv'):

  def wrapper(inputs):
    inputs_shape = tf.shape(inputs)
    b, h, w = inputs_shape[0], inputs_shape[1], inputs_shape[2]
    filters = inputs.get_shape().as_list()[-1]
    d = max(filters//r, L)

    x = inputs

    xs = []
    for m in range(1, M+1):
      if G == 1:
        _x = KL.Conv2D(filters, 3, dilation_rate=m, padding='same',
                          use_bias=False, name=name+'_conv%d'%m)(x)
      else:
        c = filters // G
        _x = KL.DepthwiseConv2D(3, dilation_rate=m, depth_multiplier=c, padding='same',
                                   use_bias=False, name=name+'_conv%d'%m)(x)

        _x = KL.Reshape([h, w, G, c, c], name=name+'_conv%d_reshape1'%m)(_x)
        _x = KL.Lambda(lambda x: tf.reduce_sum(_x, axis=-1),
                          output_shape=[b, h, w, G, c],
                          name=name+'_conv%d_sum'%m)(_x)
        _x = KL.Reshape([h, w, filters],
                           name=name+'_conv%d_reshape2'%m)(_x)

      _x = KL.BatchNormalization(name=name+'_conv%d_bn'%m)(_x)
      _x = KL.Activation('relu', name=name+'_conv%d_relu'%m)(_x)

      xs.append(_x)

    U = KL.Add(name=name+'_add')(xs)
    s = KL.Lambda(lambda x: tf.reduce_mean(x, axis=[1,2], keepdims=True),
                      output_shape=[b, 1, 1, filters],
                      name=name+'_gap')(U)

    z = KL.Conv2D(d, 1, name=name+'_fc_z')(s)
    z = KL.BatchNormalization(name=name+'_fc_z_bn')(z)
    z = KL.Activation('relu', name=name+'_fc_z_relu')(z)

    x = KL.Conv2D(filters*M, 1, name=name+'_fc_x')(z)
    x = KL.Reshape([1, 1, filters, M],name=name+'_reshape')(x)
    scale = KL.Softmax(name=name+'_softmax')(x)

    x = KL.Lambda(lambda x: tf.stack(x, axis=-1),
                      output_shape=[b, h, w, filters, M],
                      name=name+'_stack')(xs) # b, h, w, c, M
    x = Axpby(name=name+'_axpby')([scale, x])

    return x
  return wrapper

class Axpby(KL.Layer):
  """
  Do this:
    F = a * X + b * Y + ...
    Shape info:
      a:  B x 1 x 1 x C
      X:  B x H x W x C
      b:  B x 1 x 1 x C
      Y:  B x H x W x C
      ...
      F:  B x H x W x C
  """
  def __init__(self, **kwargs):
        super(Axpby, self).__init__(**kwargs)

  def build(self, input_shape):
        super(Axpby, self).build(input_shape)  # Be sure to call this at the end

  def call(self, inputs):
    """ scale: [B, 1, 1, C, M]
        x: [B, H, W, C, M]
    """
    scale, x = inputs
    f = tf.multiply(scale, x, name='product')
    f = tf.reduce_sum(f, axis=-1, name='sum')
    return f

  def compute_output_shape(self, input_shape):
    return input_shape[0:4]`

then i use this to my resnet"conv_block"
`def conv_block(input_tensor, kernel_size, filters, stage, block,
               strides=(2, 2), use_bias=True, train_bn=True):
    """conv_block is the block that has a conv layer at shortcut
    # Arguments
        input_tensor: input tensor
        kernel_size: default 3, the kernel size of middle conv layer at main path
        filters: list of integers, the nb_filters of 3 conv layer at main path
        stage: integer, current stage label, used for generating layer names
        block: 'a','b'..., current block label, used for generating layer names
        use_bias: Boolean. To use or not use a bias in conv layers.
        train_bn: Boolean. Train or freeze Batch Norm layers
    Note that from stage 3, the first conv layer at main path is with subsample=(2,2)
    And the shortcut should have subsample=(2,2) as well
    """
    nb_filter1, nb_filter2, nb_filter3 = filters
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'

    x = KL.Conv2D(nb_filter1, (1, 1), strides=strides,
                  name=conv_name_base + '2a', use_bias=use_bias)(input_tensor)
    x = BatchNorm(name=bn_name_base + '2a')(x, training=train_bn)
    x = KL.Activation('relu')(x)

    
    x = SKConv(x)

    
    x = BatchNorm(name=bn_name_base + '2b')(x, training=train_bn)
    x = KL.Activation('relu')(x)

    x = KL.Conv2D(nb_filter3, (1, 1), name=conv_name_base +
                  '2c', use_bias=use_bias)(x)
    x = BatchNorm(name=bn_name_base + '2c')(x, training=train_bn)

    shortcut = KL.Conv2D(nb_filter3, (1, 1), strides=strides,
                         name=conv_name_base + '1', use_bias=use_bias)(input_tensor)
    shortcut = BatchNorm(name=bn_name_base + '1')(shortcut, training=train_bn)
    
    x = KL.Add()([x, shortcut])
    x = KL.Activation('relu', name='res' + str(stage) + block + '_out')(x)
    return x`

i got the error :`ValueError: Layer bn2a_branch2b was called with an input that isn't a symbolic tensor. Received type: <class 'function'>. Full input: [<function SKConv.<locals>.wrapper at 0x000002BC7F741D90>]. All inputs to the layer should be tensors.`
anyone know it?
thx

**Comment by yuto3o** [comment]
I think the above code have a mistake:
replace
`x = SKConv(x)`
with
`x = SKConv(any parameters your like)(x)`
