### ISSUE TITLE
reshape

### ISSUE THREAD

**Issue by sycyjl7146** [yuto3o/SKNet-Keras#5]
in line 49

 I think "x = layers.Reshape([1, 1, filters, M],name=name+'_reshape')(x)"  may be  change to  "x = layers.Reshape([b, 1, 1, filters, M],name=name+'_reshape')(x)" because out put should be [batch_size, 1, 1, filters, M]

**Comment by yuto3o** [comment]
This document [https://keras.io/api/layers/reshaping_layers/reshape/] would help you understand this op.
