### ISSUE TITLE
Bug line 27 skconv.py 

### ISSUE THREAD

**Issue by Ambistic** [yuto3o/SKNet-Keras#7]
Hello, there is a bug caused by a mistake on line 27 of skconv.py.

I had to replace `_x` by `x` in the following lambda function
```python3
_x = layers.Lambda(lambda x: tf.reduce_sum(_x, axis=-1),
                          output_shape=[b, h, w, G, c],
                          name=name+'_conv%d_sum'%m)(_x)
```

**Comment by yuto3o** [comment]
Yes, it is a mistake. But it doesn't affect the result.
