### ISSUE TITLE
Have you tested it, can you reach the level of the paper?？

### ISSUE THREAD

**Issue by kongyan66** [yuto3o/SKNet-Keras#8]

**Comment by yuto3o** [comment]
I used it as a component in my network and not test it on the classification task.

**Comment by kongyan66** [comment]
What is the effect? I want to use it for target detection

**Comment by yuto3o** [comment]
For crowd counting task, it doesn't work.

**Comment by kongyan66** [comment]
Do you pay attention to the attention mechanism? I tested a few in ResNet50 , and found that they haven't been improved

**Comment by yuto3o** [comment]
Sorry, I focus on NLP now. And attention trick doesn't always work.

**Comment by kongyan66** [comment]
OK，Thanks
